### ISSUE TITLE
What permissions are required?

### ISSUE THREAD

**Issue by tristanz** [Azure/aci-connector-k8s#14]
I can't find any documentation on the set of permissions I need to run aci-connector.  I appear not to have permissions to ResourcementManagement APIs.

```
kubectl logs aci-connector
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code BGCVTUMKK to authenticate.
k8s pod creater/updater
container deleter
container scheduler
creating aci-connector
{ Error: The subscription 'REDACTED' could not be found.
    at client.pipeline (/app/node_modules/azure-arm-resource/lib/resource/operations/resources.js:203:19)
```

On the other hand I can run `az resource list` from the CLI and see resources in my ACI_RESOURCE_GROUP, so I'm not exactly sure why I can't use it from the API.

Any guidance?

**Comment by robotica72** [comment]
Since this is so new, Theres probably only a few people watching the issues section, so Ill take a stab at it.

Just a few questions to get a start - (Sorry if they are basic Q's - Just verifying the basics to start)

1. I would think the aci-connector yaml settings might be the issue?   Have you verified each of the settings?   The error looks like a common Azure issue when permissions arent set, and if you used all the steps from the install on here, it creates the correct permissions.

Some the settings that are returned by the CLI aren't a 1:1 in the yaml, I made that mistake on one setting when I first installed.    

Verify you subscription ID that was returned form az account list -o table   in the aci-connector.yaml file.

I would ask to see the yaml file, but its information you shouldnt post :)  One downfall to fixing the connector.

**Comment by tristanz** [comment]
So, that `SubscriptionId` I used for the above does not match the one listed in `az account list`.  However when I use the `SubscriptionId` list from `az account list`, I get the following error:

> { Error: The access token is from the wrong issuer 'https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/'. It must match the tenant 'https://sts.windows.net/719bbd25-193c-45ab-a3cc-8af651718ed8/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/719bbd25-193c-45ab-a3cc-8af651718ed8' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.

**Comment by tristanz** [comment]
Ok, so the issue is that for interactive login you still need to pass the tenantId as options object: 

```
azure.interactiveLogin({domain: tenant}, function(err, credentials) {
});
```
I'd submit a PR but I don't have a CLA in place and there is only a few line change to thread through tenant ID even when client key not specified.

**Comment by lachie83** [comment]
Hi @tristanz. The following are passed in as part of the login. See 

https://github.com/Azure/aci-connector-k8s/blob/420b411d590f3c60f28c77889beb4ff089c2dda2/connector.ts#L49-L60

**Comment by lachie83** [comment]
Hi @tristanz. Can you please let me know if this solves your issue?

**Comment by lachie83** [comment]
Closing as I believe my previous comments address this issue. Please reopen if that's not the case @tristanz
